sonar.projectKey=yoma8a2_newpro
sonar.organization=yoma8a2
sonar.projectName=newpro

# النقطة تعني فحص كل المجلد الحالي بما فيه من HTML, SQL, PHP
sonar.sources=.

# هذا السطر يضمن عدم تجاهل أي ملف بسبب اللغة
sonar.sourceEncoding=UTF-8

# أخبره هنا بملفات الـ SQL والـ HTML بوضوح
sonar.sql.file.suffixes=sql
sonar.html.file.suffixes=html,php
