sonar.projectKey=yoma8a2_newpro
sonar.organization=yoma8a2
sonar.projectName=newpro
sonar.projectVersion=1.0

# هذا السطر ضروري جداً ليخبر النظام أن يفحص المجلد الحالي
sonar.sources=.

# تحديد اللغة والترميز
sonar.language=php
sonar.sourceEncoding=UTF-8

# استثناء ملفات الاختبار أو المكتبات الخارجية (اختياري)
# sonar.exclusions=vendor/**
