sonar.projectKey=yoma8a2_newpro
sonar.organization=yoma8a2

# تأكدي أن هذه النقطة موجودة وبدون مسافات بعدها
# النقطة تعني (افحص كل شيء في المجلد الرئيسي وما تحته)
sonar.sources=.

# حددي أنواع الملفات لضمان شمولها
sonar.language=php
sonar.sourceEncoding=UTF-8
sonar.php.exclusions=**/vendor/**
