name: Build
on:
  push:
    branches:
      - main  # تأكدي أن اسم الفرع عندك main وليس master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # مهم جداً لسوناكلاود لقراءة تاريخ الكود
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # هذا موجود تلقائياً في جيت هاب
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # هذا اللي أضفتيه في الـ Secrets
