name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: SonarCloud Scan
        # هذه هي الأداة الجديدة التي لا ترفض ملفات الويب
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=yoma8a2
            -Dsonar.projectKey=yoma8a2_newpro
            -Dsonar.sources=.
            -Dsonar.exclusions=**/vendor/**,**/node_modules/**
            -Dsonar.sourceEncoding=UTF-8
